#!/usr/bin/env ruby

require 'uri'
require 'net/http'
require 'json'

bridge_url = ENV.fetch('BRIDGE_URL', 'http://localhost:50400')
compliance_tool_url = URI('https://compliance-tool-reference.ida.digital.cabinet-office.gov.uk/idp-test-run')
compliance_tool_settings = {
    idpEntityId: "#{bridge_url}/metadata",
    singleSignOnServiceUrl: "#{bridge_url}/SAML2/SSO/POST",
    idpPublicCert: 'MIIETDCCAzSgAwIBAgIQOKOHJlTEyKwuIxH4JMKa4jANBgkqhkiG9w0BAQsFADBLMQswCQYDVQQGEwJHQjEXMBUGA1UEChMOQ2FiaW5ldCBPZmZpY2UxDDAKBgNVBAsTA0dEUzEVMBMGA1UEAxMMSURBUCBUZXN0IENBMB4XDTE1MDgyNzAwMDAwMFoXDTE3MDgyNjIzNTk1OVowgYIxCzAJBgNVBAYTAkdCMQ8wDQYDVQQIEwZMb25kb24xDzANBgNVBAcTBkxvbmRvbjEXMBUGA1UEChQOQ2FiaW5ldCBPZmZpY2UxDDAKBgNVBAsUA0dEUzEqMCgGA1UEAxMhU3R1YiBJRFAgU2lnbmluZyAoMjAxNTA4MjYxNTUwMDkpMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA35xsedic10pjL4il/ZVzeYyQ+x5HAPKFbHsMG5aV+vJQC+uuvTgHDtvGFDA+ULyojJox+USvKzl506PxDBb81fgTN8ovmNY4Hq87rDphRN0szI/X8MHtxLUayzJb4+JmtaMCfZWh3MiACUztdJktpPbk6fUXvu7MtkLKMTNQjRZ/QBAs9j4e4kGE8viT3mpb81iBz5Hnj3T/PTj6lOJDVssnwUFucSvwFKW30YagP0mA98C1oe4lM/M8CiKH2O73sc+2LWC0z9AVRvDosOiTB2WHeX57+dj8uzFy/ciM3iDaxGAiNxV/wJOMBZ7Q4FlJRnv7ZFKho7RyqFxF7jsDNQIDAQABo4HzMIHwMAwGA1UdEwEB/wQCMAAwVQYDVR0fBE4wTDBKoEigRoZEaHR0cDovL29uc2l0ZWNybC50cnVzdHdpc2UuY29tL0NhYmluZXRPZmZpY2VJREFQVGVzdENBL0xhdGVzdENSTC5jcmwwDgYDVR0PAQH/BAQDAgeAMB0GA1UdDgQWBBQf7BHYhs8A4GD8PvISN8RTARjDNDAfBgNVHSMEGDAWgBRqEU1kUN/eY29XoYgf+AOVDiIEtDA5BggrBgEFBQcBAQQtMCswKQYIKwYBBQUHMAGGHWh0dHA6Ly9zdGQtb2NzcC50cnVzdHdpc2UuY29tMA0GCSqGSIb3DQEBCwUAA4IBAQA590MODC/+9taOqsLd9WofST/4NVFZxDosIAwGTtp9IwBYdF8YYGCkQfIgnvkAuXVowOkZTXTl/85QgSSh9NGZ+NoW3unHwEDBsBXiYfef3tusnAV3JlKNlA9S5WZJ2+SmU5R85qnRg0/Pa0/2l2Db5dSbXxWPGwkF7JK5Ss3snCrT06NdWOC63lB4RE9oZBTmm8ZmmTbNmoR5ElKJHR9rb54YN0Y8XjVAvEqVnFj85yDbGBMaU3Xf4iQfVz22yTrmWYLumvoTJi8oco++d4XrFJBzKsuKWHlv3Dka0hPukRSNYThIZwngGuca5YHeCaJm4wWO5dAxdstM0iafr7r/'
}

compliance_tool_request = Net::HTTP::Post.new(compliance_tool_url.path, 'Content-Type' => 'application/json')
compliance_tool_request.body = compliance_tool_settings.to_json
compliance_tool_response = Net::HTTP.start(compliance_tool_url.hostname, compliance_tool_url.port, use_ssl: compliance_tool_url.scheme == 'https') { |http|
  http.request(compliance_tool_request)
}

puts compliance_tool_response.header.fetch('location')

